#
# Network of Innovators Dockerfile for db
#
# https://github.com/govlab/ottawa-final
#

FROM postgres:9.4
MAINTAINER John Krauss <john@thegovlab.org>

RUN apt-get update
RUN apt-get install -yqq postgresql-9.4-plv8
